import Head from "next/head";
import { MagnifyingGlassIcon } from '@heroicons/react/24/solid'

export default function Home() {
  return (
    <>
      <Head>
        <title>Condition Research</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-4">
        <p className="text-md font-semibold">
          Enter your condition and receive the latest research, treatments, and data.
        </p>
        <div>
          <div className="mt-2 flex">
            <input
              type="email"
              name="email"
              id="email"
              className="outline-none block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-emerald-600 sm:text-sm sm:leading-6"
              placeholder=""
            />
            <div className="m-1" />
            <button
              type="button"
              className="flex items-center rounded-md bg-emerald-600 px-2.5 py-1.5 text-sm font-semibold text-white shadow-sm hover:bg-emerald-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-emerald-600"
            >
              Search
              <MagnifyingGlassIcon className="ml-1 text-white h-4 w-4" />
            </button>
          </div>
        </div>
      </main>
    </>
  )
}
